- name: variables from args
  hosts: local
  connection: local 
  tasks:
  - name: print the corse info
    ansible.builtin.debug:
      msg: "Course Name is:  {{COURSE }},Duratioin:{{DURATION}}, Trainer: {{TRAINER}}"