- name: conditions
  hosts: local
  connection: local
  # ansible collects the info of target server, before it executes any other fact
  vars:
    number: 12
  tasks:
  - name: facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"