- name: Install packages
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
     name: "{{ item }}"
     state: latest
    loop:
    - nginx
    - mysql
    - zip