---
- name: Install MySQL server on Ubuntu
  hosts: dbserver
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysql
        state: started
        enabled: yes


  