---
- name: Install MySQL server on Linux
  hosts: dbserver
  become: yes

  tasks:
    - name: Update package cache
      yum:
        update_cache: yes

    - name: Install MySQL server
      yum:
        name: mysql-server
        state: present

    - name: Ensure MySQL service is running and enabled
      service:
        name: mysqld
        state: started
        enabled: yes
